---
- name: Test Artifacts
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure artifacts directory exists
      file:
        path: "/tmp/artifacts"
        state: directory
        mode: '0777'
      delegate_to: localhost

    - name: Get hostname
      command: hostname
      register: host_info

    - name: Create test content
      copy:
        content: |
          This is a test artifact
          Hostname: {{ host_info.stdout }}
          Created at: {{ lookup('pipe', 'date') }}
        dest: "/tmp/artifacts/test.txt"
      delegate_to: localhost
