---
- name: Test Artifacts
  hosts: all  # AWX will use the host you select
  gather_facts: false
  tasks:
    - name: Get hostname
      command: hostname
      register: host_info

    - name: Create test content
      copy:
        content: |
          This is a test artifact from host: {{ host_info.stdout }}
          Created at: {{ ansible_date_time | default(lookup('pipe', 'date')) }}
        dest: "{{ lookup('env', 'AWX_ARTIFACT_DIR', default='/tmp/artifacts') }}/test_{{ host_info.stdout }}.txt"
      delegate_to: localhost

    - name: Show file was created
      debug:
        msg: "Created artifact file for host {{ host_info.stdout }}"
