---
- name: Test Artifacts
  hosts: all
  gather_facts: false
  tasks:
    - name: Debug inventory
      debug:
        msg: 
          - "Inventory host: {{ inventory_hostname }}"
          - "Current working directory: {{ lookup('pipe', 'pwd') }}"
      delegate_to: localhost

    - name: Show current directory contents
      command: ls -la
      register: ls_output
      delegate_to: localhost

    - name: Debug directory contents
      debug:
        var: ls_output.stdout_lines
      delegate_to: localhost

    - name: Create simple file
      copy:
        content: "Test content"
        dest: "./test.txt"
      delegate_to: localhost
